"""
bdf_bl_visualize.py — BL-176 AK-8 Visualisierung
Erzeugt Mermaid-Graph + ASCII-Tabelle aus interest_radius_snapshot.

CLI:
  py -3 bdf_bl_visualize.py --vault-root=... --format=mermaid|ascii|both --output=graph.md

BL-176 PL-176-024
"""

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Any

# Bucket-Farben fuer Mermaid-Nodes
BUCKET_COLORS = {
    0: "fill:#e8f5e9,stroke:#4caf50",   # Gruen: foundation / serial
    1: "fill:#e3f2fd,stroke:#2196f3",   # Blau: Bucket 1
    2: "fill:#fff3e0,stroke:#ff9800",   # Orange: Bucket 2
    3: "fill:#fce4ec,stroke:#e91e63",   # Pink: Bucket 3
    4: "fill:#f3e5f5,stroke:#9c27b0",   # Lila: Bucket 4
}
DEFAULT_BUCKET_COLOR = "fill:#eceff1,stroke:#607d8b"  # Grau: weitere Buckets

PRIORITY_SYMBOLS = {
    "KRITISCH": "[!]",
    "HOCH": "[H]",
    "MITTEL": "[M]",
    "NIEDRIG": "[L]",
}


def load_snapshot(vault_root: str) -> Dict[str, Any]:
    """Laedt interest_radius_snapshot aus _factory_manifest.md oder direkt aus JSON-Files."""
    interest_radius_dir = Path(vault_root) / "Vault" / "Meta" / "interest_radius"

    snapshot: Dict[str, Any] = {}

    buckets_file = interest_radius_dir / "bl_parallel_buckets.json"
    matrix_file = interest_radius_dir / "bl_dependency_matrix.json"
    sequence_file = interest_radius_dir / "bl_sequence.json"

    if buckets_file.exists():
        with open(buckets_file, encoding="utf-8") as f:
            snapshot["buckets"] = json.load(f)

    if matrix_file.exists():
        with open(matrix_file, encoding="utf-8") as f:
            snapshot["matrix"] = json.load(f)

    if sequence_file.exists():
        with open(sequence_file, encoding="utf-8") as f:
            snapshot["sequence"] = json.load(f)

    return snapshot


def get_bucket_for_bl(bl_id: str, buckets_data: Dict) -> int:
    """Gibt Bucket-Index fuer eine BL-ID zurueck (-1 wenn nicht gefunden)."""
    if not buckets_data:
        return -1
    for bucket_key, bucket_info in buckets_data.get("buckets", {}).items():
        bls = bucket_info.get("bls", [])
        if bl_id in bls:
            idx = int(bucket_key.replace("bucket-", ""))
            return idx
    return -1


def generate_mermaid(snapshot: Dict[str, Any]) -> str:
    """Erzeugt Mermaid-Graph aus interest_radius_snapshot.

    Nodes = BLs (Color nach Bucket), Edges = dependencies.
    """
    buckets_data = snapshot.get("buckets", {})
    matrix_data = snapshot.get("matrix", {})
    matrix = matrix_data.get("matrix", {})

    lines = ["```mermaid", "graph TD"]
    lines.append("    %% BL Dependency Graph — generated by bdf_bl_visualize.py")
    lines.append(f"    %% Generated: {datetime.now().isoformat()[:19]}")
    lines.append("")

    if not matrix:
        lines.append("    EMPTY[No BLs in snapshot]")
        lines.append("```")
        return "\n".join(lines)

    # Nodes definieren
    all_bls = list(matrix.keys())
    for bl_id in all_bls:
        safe_id = bl_id.replace("-", "_")
        bucket_idx = get_bucket_for_bl(bl_id, buckets_data)
        bucket_label = f"B{bucket_idx}" if bucket_idx >= 0 else "B?"
        lines.append(f"    {safe_id}[\"{bl_id} {bucket_label}\"]")

    lines.append("")

    # Edges (Dependencies)
    edge_count = 0
    for bl_id, deps in matrix.items():
        safe_bl = bl_id.replace("-", "_")
        for dep in deps:
            safe_dep = dep.replace("-", "_")
            lines.append(f"    {safe_dep} --> {safe_bl}")
            edge_count += 1

    lines.append("")

    # Stil-Klassen fuer Buckets
    for bucket_key, bucket_info in buckets_data.get("buckets", {}).items():
        bucket_idx = int(bucket_key.replace("bucket-", ""))
        color = BUCKET_COLORS.get(bucket_idx, DEFAULT_BUCKET_COLOR)
        class_name = f"bucket{bucket_idx}"
        lines.append(f"    classDef {class_name} {color}")
        bls = bucket_info.get("bls", [])
        if bls:
            safe_ids = ",".join(b.replace("-", "_") for b in bls)
            lines.append(f"    class {safe_ids} {class_name}")

    lines.append("```")
    lines.append(f"\n_Nodes: {len(all_bls)}, Edges: {edge_count}_")

    return "\n".join(lines)


def generate_ascii(snapshot: Dict[str, Any]) -> str:
    """Erzeugt ASCII-Tabelle aus interest_radius_snapshot."""
    buckets_data = snapshot.get("buckets", {})
    sequence_data = snapshot.get("sequence", {})
    matrix_data = snapshot.get("matrix", {})

    sequence = sequence_data.get("sequence", [])
    matrix = matrix_data.get("matrix", {})
    bucket_count = buckets_data.get("bucket_count", 0)

    lines = []
    lines.append("# BL Interest-Radius Snapshot")
    lines.append(f"Generated: {datetime.now().isoformat()[:19]}")
    lines.append(f"BLs: {len(matrix)}, Buckets: {bucket_count}")
    lines.append("")

    if not sequence and not matrix:
        lines.append("(No data in snapshot)")
        return "\n".join(lines)

    # Tabellen-Header
    header = f"{'BL-ID':<12} {'Bucket':<8} {'Priority':<10} {'Dependencies'}"
    lines.append(header)
    lines.append("-" * 60)

    display_list = sequence if sequence else list(matrix.keys())
    for bl_id in display_list:
        bucket_idx = get_bucket_for_bl(bl_id, buckets_data)
        bucket_str = f"B{bucket_idx}" if bucket_idx >= 0 else "?"
        deps = matrix.get(bl_id, [])
        dep_str = ", ".join(deps) if deps else "(none)"
        lines.append(f"{bl_id:<12} {bucket_str:<8} {'?':<10} {dep_str}")

    lines.append("-" * 60)

    # Bucket-Zusammenfassung
    lines.append("")
    lines.append("## Bucket Summary")
    for bucket_key, bucket_info in buckets_data.get("buckets", {}).items():
        bucket_idx = int(bucket_key.replace("bucket-", ""))
        bls = bucket_info.get("bls", [])
        is_serial = not bucket_info.get("parallel", True)
        mode = "serial" if is_serial else "parallel"
        lines.append(f"  {bucket_key} [{mode}]: {', '.join(bls) if bls else '(empty)'}")

    return "\n".join(lines)


def build_output(snapshot: Dict[str, Any], fmt: str) -> str:
    """Baut kombinierten Output basierend auf Format-Flag."""
    if fmt == "mermaid":
        return generate_mermaid(snapshot)
    elif fmt == "ascii":
        return generate_ascii(snapshot)
    else:  # both
        return generate_mermaid(snapshot) + "\n\n---\n\n" + generate_ascii(snapshot)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="BDF BL Visualizer — Mermaid + ASCII aus interest_radius_snapshot"
    )
    parser.add_argument("--vault-root", required=True, help="Pfad zum Vault-Root")
    parser.add_argument(
        "--format",
        choices=["mermaid", "ascii", "both"],
        default="both",
        help="Ausgabe-Format (default: both)",
    )
    parser.add_argument(
        "--output",
        default=None,
        help="Ausgabe-Datei (default: stdout)",
    )
    args = parser.parse_args()

    if not os.path.isdir(args.vault_root):
        print(f"ERROR: vault-root nicht gefunden: {args.vault_root}", file=sys.stderr)
        return 1

    snapshot = load_snapshot(args.vault_root)
    if not snapshot:
        print("WARNING: Kein interest_radius_snapshot gefunden. Leere Ausgabe.", file=sys.stderr)

    output = build_output(snapshot, args.format)

    if args.output:
        output_path = Path(args.output)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(output)
        print(f"Ausgabe geschrieben: {output_path}", file=sys.stderr)
    else:
        print(output)

    return 0


if __name__ == "__main__":
    sys.exit(main())
